travis:
  secure:
    BINSTAR_TOKEN: Io0xiyYtdeq8J/b+0b40mWeQsn/FgQJ2+T0+4KbIjG0u+h2QbQyRlBtR+GF5uVEswZzv0lVlJZrTOnhFISritMLLoBP3zQkx/1x/+uTedmYWOALYgg2UBu9RT/1LpHeyXcfIlt6S7hR17jU0sEbu2iJVCq2viMKD+ePJpAa+CL3njWLJqWHgn3D13UvCZzbgafiyWI7T/krn9zLnLNGnGFQl2dxpg8r1+OW7IHiohtFDNPT9i00TyVelB5/6MwhgdKH1ScVOSLtbMvc/wGLKV3L6aVB/qz+zuauqlEIJHq3bGmhiYiyaRXs8uyH9rEt7Q77TH2hgvRKpVVHQzRhNF/jt8EozhevxRwhCG9B4KL8kwrTr6Gl/I6A2E0ymxETEpdgvR/m9YKCCMyMwMsKDbiypLnbzK57Gdr7wWJFGJ12G6vLd0WZqxRmdWIw4eXB5pBT9tLfv1KGo+mtrqvEov9Z8pVXZqqlMgvvKlevQnUSwbe0rifzVwBH7pl1hjqDWym8ZXfHvn2k4+LnSDkhCtqmyIf5/l3p5oz2jgXGdxAJxQEYF5rZRw25shYUzQnjx2QyNVV7ARznltop5Qy9+LIl89Nz9lhfIPlVkO83TjLuy81xEU1RmeFnnta13BFTtBpUCX+p4jzM0y7IC5cnfIWum33yCQHchE0Cfb89W7yk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
