travis:
  secure:
    BINSTAR_TOKEN: g78nvBcNKxT48wzQRd4e7fn9H2ZhielHZKqgc5h4TxnUx20/TF+8zuBgMOCf+IyyEkUm0s8ZWKDYv43Ue8P7gpHQMdLzjqE44nlLqwwdtXLOCjcB6qKYH1q/sMCjQ8dffouaHlbQm5no5M8cY6e7dweLBLt87tNaXSg+MOETEDxhbFiAMFJe5ri1tuSDafBWf9g4Y17wjiCwGSqbjnQIyHKuVUQ+Iupe+lsxGB2dxu2MIVJhnlT7qMTPgphDTTdeGyMufcVrYBRjbDVfbzM7bJlWVoE19PjfLX3E/0UVTx1fNh+qZLQnd0v9TEk0MljQ1Ze4sLB9xXcPkP0ieQ11HPxBVTHD9KQrvKA9pdT/IB2XEU7pYR6gA2tTJmDaOuTRT+9dHaMaolqamXjYm/nLAX+0LMpsowFcwNSGfX26dBikKqHoBiSZd72hQHkW8GoIkwl5pKPFajjT70TSPC1fypG7LMX9xOf5vuJ9o4O9rUwE32rdee1LsEh3Dy79A1U32tm1RQlLORiguFuF3aIcS2d0nSGEzuoV49N4s8hR55KLljzQbveOYBTA+M/iT+lG2xs4kueDI3nd86EkpPvpdFucQO+XR5QqjlhxD4TqRVgop/4wQOXDDZzIlvt6mNcS9nCXQwsBDEiiAASl/ciYiaF6qb6858Pt89+DlDfJIPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
